### ISSUE TITLE
注册功能

### ISSUE THREAD

**Issue by zwpaper** [BeautyLive/Documents#1]
用小程序作为移动端，我们可以直接用微信登陆，少一个注册登陆的环节，先把功能跑起来，如何？
@LuckyHawk

**Comment by LuckyHawk** [comment]
可




发自网易邮箱大师
在2017年03月31日 23:02，PapEr 写道：

用小程序作为移动端，我们可以直接用微信登陆，少一个注册登陆的环节，先把功能跑起来，如何？
@LuckyHawk
